Adds @solana/wallet-adapter
blockworks-foundation/mango-ui-v3 pull request #186
Opened 2022-03-15 14:12 UTC by kierangillen

## Switch wallet sign on to use @solana/wallet-adapter

Adds [@solana/wallet-adapter](https://github.com/solana-labs/wallet-adapter) and removes our custom `useWallet` hook. The new wallet adapter package includes a new `useWallet` hook, but we are still relying heavily on the `mangoStore` wallet throughout the codebase. This PR stitches the Solana Labs adapter with our store, which allows us to still use the mango store wallet without introducing a large code update. We should incrementally refactor components to use the new system.

- Screenshot of new `Connect` button (removes carrot and dropdown):

<img width="480" alt="Screen Shot 2022-03-15 at 2 52 01 PM" src="https://user-images.githubusercontent.com/21182806/158395312-6c6df567-72b0-4222-a388-ff6c47d676ce.png">

- Screenshot of the Wallet selector modal (which should be reskinned):

<img width="1183" alt="Screen Shot 2022-03-15 at 2 46 50 PM" src="https://user-images.githubusercontent.com/21182806/158396726-494a7588-fee2-41ff-9774-7e0217e7dc3c.png">

2022-03-15 14:19 UTC, kierangillen commented on pages/account.tsx
> -  }, [connected])
I'm not sure what the purpose of this code block was for? Refreshing the page when the wallet connected? But this was creating an infinite loop using the new `connected` hook and seemed to be to be unnecessary.

2022-03-15 14:45 UTC, mschneider commented on stores/useMangoStore.tsx
> +const DEFAULT_MANGO_GROUP_NAME = process.env.NEXT_PUBLIC_GROUP || 'devnet.2'
shouldn't be updated

2022-03-15 14:57 UTC, kierangillen commented
@mschneider Thanks yeah, the build is broken because I need to update the `WalletAdapter` type in the Client. PR for that is here: https://github.com/blockworks-foundation/mango-client-v3/pull/72 - sort of a chicken or the egg problem there.

2022-03-15 15:23 UTC, kierangillen commented
Moving this PR to draft as we work out the UX/UI

2022-03-15 16:15 UTC, tjshipe requested changes

2022-03-15 16:15 UTC, tjshipe commented on @types/types.tsx
>  export interface WalletAdapter {
Can we get rid of this type and just import the WalletAdapter type from the solana pkg?

2022-03-15 16:15 UTC, tjshipe commented on components/WalletProvider.tsx
> +      await actions.fetchMangoGroup()
This shouldn't be needed here. The mango group should be loaded on page load.

2022-03-15 16:15 UTC, tjshipe commented on components/index.tsx
> +export * from './AccountInfo'
This is great, thanks for adding 🙏

2022-03-15 16:15 UTC, tjshipe commented on pages/account.tsx
> -  }, [connected])
I think this may be needed for when you're viewing someone elses mango account. Lets sync up on this one

2022-03-16 13:39 UTC, kierangillen commented on @types/types.tsx
>  export interface WalletAdapter {
Unfortunately not yet. For now I'm coercing the WalletAdapter to match this type, but they don't match. Once we transition completely do using the WalletAdapter we can.

2022-03-16 14:02 UTC, kierangillen commented on components/WalletSuggestionModal.tsx
> +export const WalletSuggestionModal: React.FC<Props> = ({ isOpen, onClose }) => {
@saml33 Here's the `WalletSuggestionModal` we discussed.

2022-03-16 23:42 UTC, saml33 commented on components/WalletSuggestionModal.tsx
> +export const WalletSuggestionModal: React.FC<Props> = ({ isOpen, onClose }) => {
Cool, thanks.

An issue with only showing detected wallets is it won't show web-based (eg Sollet web). Maybe in the dropdown we need a small list of detected/popular and the last item is "More Options" which when clicked closes the dropdown and opens a modal with a complete list. Could also have an expandable section in the modal "Don't have a wallet?" where we could make recommendations. What do you think?

Also, before interacting with the button it should probably have something selected by default. I clicked the Connect button and nothing happens which is maybe more confusing that it trying to connect to a wallet I don't intend to use. It says the wallet name under connect anyway so likely users will see that and change it before connecting

2022-03-17 10:34 UTC, kierangillen commented on components/WalletSuggestionModal.tsx
> +export const WalletSuggestionModal: React.FC<Props> = ({ isOpen, onClose }) => {
I think for now let's include the wallets that aren't extensions, that are common, always and then show first the wallets that are installed, that covers all of our bases. We can later include the modal but I don't want to add more scope to this if not needed now.

2022-03-17 16:29 UTC, merged