Show referral fees history and total
blockworks-foundation/mango-ui-v3 pull request #190
Opened 2022-03-16 15:33 UTC by l2succes

- We now have the ability to see the referral fee history and total amount accrued for a given customer 

## Preview

<img width="1728" alt="Screen Shot 2022-03-15 at 6 44 06 PM" src="https://user-images.githubusercontent.com/296775/158618287-293827c2-9c56-438b-94f3-ea1e12b59957.png">

2022-03-17 02:08 UTC, tjshipe commented
@l2succes I tested this on mainnet and it displayed the data similar to your screenshot. The only 2 issues there are the Referral ID column can be completely removed, and the Fee Earned column on the right is empty. 

I think it's empty because the wrong key is being used. It should display the `referral_fee_accrual` from the api response. Also the fee accrual amounts will be low so you can use `usdFormatter` and pass in 4 as the second argument to show more decimals.

2022-03-17 04:05 UTC, l2succes commented
@tjshipe Got it, thanks for the review. I'll get that fixed and push an update

2022-03-17 17:11 UTC, l2succes commented
@tjshipe I fixed the fields to pull in the correct data and removed that unused Referral ID column

2022-03-17 18:40 UTC, tjshipe requested changes
If you reduce the width of the browser window, you can see the mobile view. Looks like there is a typo from our original mockups on line 470, should be "fee-earned". Also, should call the same `usdFormatter` with 4 decimals on line 479 to display the fee on mobile widths.

2022-03-17 18:40 UTC, tjshipe commented on pages/referral.tsx
> +                                </Td>
The second argument to `usdFormatter` should probably be 4 so we show more decimals in the table

2022-03-18 02:35 UTC, saml33 commented on pages/referral.tsx
> +                                </Td>
I think if we do this:

export const usdFormatter = (value, decimals = 2, currency = true) => {
  if (decimals === 0) {
    value = Math.abs(value)
  }
  const fractionDigits =
    value < 1 ? countLeadingZeros(value) + decimals : decimals
  const config = currency ? { style: 'currency', currency: 'USD' } : {}
  return new Intl.NumberFormat('en-US', {
    ...config,
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
  }).format(value)
}

We won't need to pass decimals to number < 1

2022-03-18 02:39 UTC, saml33 commented
<img width="239" alt="Screen Shot 2022-03-18 at 1 11 57 pm" src="https://user-images.githubusercontent.com/30796577/158926934-29a803f9-2c80-49be-a6dd-b4bfc9a097bc.png">

We should settle on a date/time format. I think we have at least 3 including what you have done. I think your date format is the best as dd/mm/yyyy is prob confusing for USA. I would have your date format with the time on a new line as in the screenshot. What do you guys think?

2022-03-18 02:45 UTC, saml33 commented
<img width="445" alt="Screen Shot 2022-03-18 at 1 09 14 pm" src="https://user-images.githubusercontent.com/30796577/158927351-70da85ad-314f-4950-a849-6201a98b82f3.png">

As Tyler mentioned, a few issues on mobile. You can remove pb-4 from this set of classes 'grid grid-flow-row grid-cols-2 gap-4 pb-4'

There is a key error in the console

2022-03-18 17:39 UTC, l2succes commented
@saml33 I agree, the date `18 Mar 2022` format with the time on a new line would look best. I'll make that change. Might make sense to extract this into a reusable component at some point

2022-03-18 18:59 UTC, l2succes commented
![Screen Shot 2022-03-18 at 2 42 08 PM](https://user-images.githubusercontent.com/296775/159064720-1c98b88e-b91a-456d-abcd-46c6021e4882.png)
![Screen Shot 2022-03-18 at 2 45 38 PM](https://user-images.githubusercontent.com/296775/159065076-9bf3b714-321b-40ca-8d8b-364581919e7c.png)

2022-03-21 00:27 UTC, merged