Cancel all button
blockworks-foundation/mango-ui-v3 pull request #275
Opened 2022-05-18 01:31 UTC by sircrusher

- Added a cancel-all button to Perp Markets. Both desktop and mobile views.
- 1 issue where the initial transaction notification does not clear after the success notification.

2022-05-18 01:38 UTC, tjshipe requested changes

2022-05-18 01:38 UTC, tjshipe commented on components/OpenOrdersTable.tsx
> +        )
it looks like `cancelAllPerpOrders` returns an array of txids

you can loop over the array of txids to dismiss the pending notifications. here is an example: https://github.com/blockworks-foundation/mango-ui-v3/blob/main/components/AccountInfo.tsx#L102

2022-05-18 02:32 UTC, sircrusher commented on components/OpenOrdersTable.tsx
> +        )
you were right. this fixed it.

2022-05-18 20:40 UTC, tjshipe commented
Approved. Pinging @saml33 for a review on this one to double check design before merging.

2022-05-18 20:40 UTC, tjshipe approved these changes

2022-05-26 10:00 UTC, saml33 commented
Can we have it so the button persists when you view other perp markets? The Cancel All button could be inline with the first order for that market (only show if there is more than one order for the same market). We might need to change the styling of the Edit/Cancel buttons to make it work but I can help with that if you want.

2022-05-26 10:11 UTC, sircrusher commented
> 

The button currently does persist on other perp markets, as long as there is at least 1 open order for the market you are currently viewing. I have tagged you on a comment for the line that determines this for the desktop view.

If I have misunderstood your request, please let me know 🤙

2022-05-26 10:24 UTC, saml33 commented
@sircrusher yeah, I mean if I'm viewing BTC-PERP and I have multiple SOL-PERP orders (which I can see in the table) it might be nice to be able to cancel all of the SOL-PERP orders from the BTC-PERP page.

The first order of a market with multiple orders could have the cancel all button beside the cancel button

2022-06-10 23:35 UTC, sircrusher commented
I moved the button to the orders row and made it red.

Button shows up on every perp order of the same contract if there are 2 or more orders for the same contract.

Desktop and mobile screenshots below:

![image](https://user-images.githubusercontent.com/14029934/173161762-7943acd1-7b75-406a-aa34-1e56af969f41.png)
 and
![image](https://user-images.githubusercontent.com/14029934/173161815-9d04c522-a742-4ddb-93b5-d8fc66a7fc05.png)

2022-06-10 23:45 UTC, sircrusher commented
I can't see any details on the failed check. Get 404 when I try to view them.

2022-06-11 10:59 UTC, godmodegalactus commented
We can update this PR to include cancel all spot orders too.
@sircrusher should I update it?

2022-06-11 17:11 UTC, sircrusher commented
> We can update this PR to include cancel all spot orders too. @sircrusher should I update it?

sure, go ahead :)

2022-07-02 11:21 UTC, merged